ChoNongSan.CtvWeb/Controllers/XetNapTienController.cs
using ChoNongSan.ApiUsedForWeb.ApiService;
using ChoNongSan.ViewModels.Common;
using ChoNongSan.ViewModels.Requests.Common;
using ChoNongSan.ViewModels.Requests.NapTien;
using ChoNongSan.ViewModels.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChoNongSan.CtvWeb.Controllers
{
	[Authorize]
	public class XetNapTienController : Controller
	{
		private readonly INapTienApi _napTienApi;
		private readonly IConfiguration _config;

		public XetNapTienController(IConfiguration config, INapTienApi napTienApi)
		{
			_napTienApi = napTienApi;
			_config = config;
		}

		public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 5)
		{
			var request = new GetPagingCommonRequest()
			{
				Keyword = keyword,
				Roles = 2,
				PageIndex = pageIndex,
				PageSize = pageSize
			};
			var UserId = Convert.ToInt32(User.Claims.Where(x => x.Type == "Id").Select(c => c.Value).SingleOrDefault());
			ViewBag.CTV = UserId;
			var data = await _napTienApi.GetListNapTien(UserId, 2, request);
			var obj = (JObject)JsonConvert.DeserializeObject(data);

			var result = obj["data"].ToObject<PageResult<NapTienVm>>();
			ViewBag.Keyword = keyword;
			ViewBag.Link = "/XetNapTien";
			ViewBag.Obj = result;
			return View(result);
		}
		[HttpPost]
		public async Task<JsonResult> Duyet(LichSuNapTienRequest request)
		{
			var data = await _napTienApi.CreateOrUpdate(request);
			return Json(data);
		}
	}
}

ChoNongSan.CtvWeb/Views/Shared/_CtvLayout.cshtml
@using System.Linq;
@using System.Security.Claims;
@{
    var avatar = User.Claims.Where(x => x.Type == "Avatar")
        .Select(c => c.Value).SingleOrDefault();
    if (String.IsNullOrEmpty(avatar)) { avatar = "/assets/images/avatars/avatar-null.png"; }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Cộng Tác Viên</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/assets/images/logo/logo1.png">

    <!-- page css -->
    <!-- Core css -->
    <link href="~/assets/css/app.min.css" rel="stylesheet">
</head>
<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark my-auto  ">
                    <a class="" href="javascript:void(0)">
                        <img style="height:45px" src="~/assets/images/logo/logo-chu-removebg.png" alt="Logo" />
                        <img class="logo-fold mx-auto" style="height:35px" src="~/assets/images/logo/logo1.png" />
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="index.html">
                        <img src="~/assets/images/logo/logo-white.png" alt="Logo">
                        <img class="logo-fold" src="~/assets/images/logo/logo-fold-white.png" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle m-r-120">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="d-lg-block d-none">
                            <form class="m-l-150 d-flex" asp-action="Index" method="get">
                                <div class="input-affix" style=" width:500px">
                                    <i class="prefix-icon anticon anticon-search"></i>
                                    <input name="keyword" value="@ViewBag.Keyword" type="text" class="form-control" placeholder="Tìm kiếm">
                                    <button class="btn btn-primary m-r-5" style="margin-left:20px" type="submit">Tìm</button>
                                    @if (ViewBag.Obj != null && ViewBag.Keyword != null)
                                    {
                                        <button type="button" onclick="window.location.href='@ViewBag.Link'" class="btn btn-default m-r-5" style="margin-left:20px">Reset</button>
                                    }
                                </div>
                            </form>
                        </li>
                        <li class="d-lg-none">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#search-drawer">
                                <i class="anticon anticon-search"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">

                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-25">
                                    <img src="@avatar" style="height:40px" alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile" >
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img style="height:40px" src="@avatar" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold">@User.Identity.Name</p>
                                            <p class="m-b-0 opacity-07">Cộng Tác Viên</p>
                                        </div>
                                    </div>
                                </div>
                                <a asp-controller="User" asp-action="Logout" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Đăng xuất</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Header END -->
            <!-- Side Nav START -->
            @await Html.PartialAsync("_SideNavPartialView.cshtml")

            <!-- Side Nav END -->
            <!-- Page Container START -->
            <div class="page-container">

                <!-- Content Wrapper START -->
                <div class="main-content">

                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Content Wrapper END -->
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <span class="d-flex mx-auto m-b-0 align-items-center">Bản quyền © 2021. Phát triển bởi <i class="mx-1 fa fa-heart text-danger"></i> VVT</span>
                    </div>
                </footer>
                <!-- Footer END -->
            </div>
            <!-- Page Container END -->
            <!-- Search Start-->
            <div class="modal modal-left fade search" id="search-drawer">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header justify-content-between align-items-center">
                            <h5 class="modal-title">Tìm kiếm</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <i class="anticon anticon-close"></i>
                            </button>
                        </div>
                        <div class="modal-body scrollable">
                            <form asp-action="Index">
                                <div class="input-affix">
                                    <i class="prefix-icon anticon anticon-search"></i>
                                    <input name="keyword" value="@ViewBag.Keyword" type="text" class="form-control" placeholder="Nhập tìm kiếm">
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-primary d-flex mx-auto">
                                        Tìm
                                    </button>

                                </div>
                            </form>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            <!-- Search End-->
        </div>
    </div>

    <!-- Core Vendors JS -->
    <script src="~/assets/js/vendors.min.js"></script>

    <!-- page js -->
    <script src="~/assets/vendors/chartjs/Chart.min.js"></script>
    <script src="~/assets/js/pages/dashboard-default.js"></script>
    <script src="~/assets/vendors/chartjs/Chart.min.js"></script>
    <!-- Core JS -->
    <script src="~/assets/js/app.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false);
</body>
</html>

ChoNongSan.CtvWeb/Views/Shared/_SideNavPartialView.cshtml
<div class="side-nav">
	<div class="side-nav-inner">
		<ul class="side-nav-menu scrollable">
			<li class="nav-item dropdown open mt-4">
				<a class="dropdown-toggle active" asp-controller="TinDang" asp-action="Index">
					<span class="icon-holder">
						<i class="anticon anticon-dashboard"></i>
					</span>
					<span class="title">Duyệt tin đăng</span>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="dropdown-toggle active" asp-controller="XetNapTien" asp-action="Index">
					<span class="icon-holder">
						<i class="anticon anticon-dashboard"></i>
					</span>
					<span class="title">Quản lý nạp tiền</span>
				</a>
			</li>
			<li class="nav-item dropdown ">
				<a class="dropdown-toggle" asp-controller="User" asp-action="CapNhatTaiKhoan">
					<span class="icon-holder">
						<i class="far fa-user-circle"></i>
					</span>
					<span class="title">Cập nhật tài khoản</span>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="dropdown-toggle" asp-controller="User" asp-action="DoiMatKhau">
					<span class="icon-holder">
						<i class="anticon anticon-sync"></i>
					</span>
					<span class="title">Đổi mật khẩu</span>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="dropdown-toggle" asp-controller="User" asp-action="Logout">
					<span class="icon-holder">
						<i class="anticon font-size-16 anticon-logout"></i>
					</span>
					<span class="title">Đăng xuất</span>
				</a>
			</li>
		</ul>
	</div>
</div>